language: c++

addons:
  apt:
    packages:
     - cmake
     - gcc-6.5
     - g++-6.5
     - qtbase5-dev
     - libqt5opengl5-dev
     - libboost-dev
     - libboost-regex-dev
     - libboost-system-dev
     - libboost-program-options-dev
     - libboost-filesystem-dev
     - libboost-iostreams-dev
     - libeigen3-dev
     - libmysqlclient-dev
     - libmysql++-dev
     - libsqlite3-dev
     - liblog4cpp5-dev
     - libgdal-dev
     - libtinyxml2-dev
     - libarchive-dev
     - libjsoncpp-dev
     - libtbb-dev

compiler:
 - gcc
# - clang

script:
 - export CC=gcc-6
 - export CXX=g++-6
 - mkdir build
 - cd build
 - cmake ..
 - cmake --build . -- -j2

